export const URLS=[
    "https://eira-collections.onrender.com/health",
    "https://task-manager-taskly.onrender.com/health",
    "https://lingugram.onrender.com/health",
    "https://activator-backend.onrender.com/health",
    "https://whisprgram.onrender.com/health",
    "https://hushline-chatapp.onrender.com",
    "https://hushline-messagebroker-service.onrender.com",
    "https://hushline-cache-service.onrender.com",
    "https://hushline-loadbalancer-service.onrender.com/health",
    "https://hushline-backend-service01.onrender.com",
    "https://hushline-backend-service02.onrender.com",
    "https://hushline-backend-service03.onrender.com",
    "https://hushline-backend-service04.onrender.com",
    "https://hushline-backend-service05.onrender.com",
]
